# Generated by Django 3.2.13 on 2024-09-03 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import moxutils.views


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.SlugField(default='GP', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moxutils_customergroup_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(blank=True, null=True)),
                ('surname', models.SlugField(validators=[moxutils.views.validate_simple_name])),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('CustomerGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_group_customer', to='moxutils.customergroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moxutils_customer_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
    ]
